# Generated by Django 5.2 on 2025-05-05 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('total_steps', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HuntStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('clue', models.TextField(max_length=500)),
                ('img', models.ImageField(upload_to='')),
                ('hint', models.TextField(max_length=300)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hunts.hunt')),
            ],
        ),
    ]
