# Generated by Django 5.2 on 2025-05-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0002_alter_huntstep_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huntstep',
            name='img',
            field=models.ImageField(upload_to='list/'),
        ),
    ]
