# Generated by Django 5.2 on 2025-05-08 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0003_alter_huntstep_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huntstep',
            name='img',
            field=models.ImageField(upload_to='hunt_steps/'),
        ),
    ]
