# Generated by Django 5.2 on 2025-05-13 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0004_alter_huntstep_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='huntstep',
            old_name='name',
            new_name='hunt',
        ),
    ]
