# Generated by Django 5.2 on 2025-05-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0005_rename_name_huntstep_hunt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huntstep',
            name='img',
            field=models.ImageField(upload_to='huntsteps/'),
        ),
    ]
