# Generated by Django 5.2 on 2025-06-11 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0006_alter_huntstep_img'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunt',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hunts', to='users.user'),
        ),
        migrations.AddField(
            model_name='hunt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
