# Generated by Django 5.2 on 2025-06-27 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0008_alter_hunt_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hunt',
            name='total_steps',
        ),
    ]
