# Generated by Django 5.2.5 on 2025-09-02 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0009_remove_hunt_total_steps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hunt',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='linked_hunts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HuntScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('top_score', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('hunt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hunts.hunt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
