# Generated by Django 5.2.6 on 2026-05-02 23:02

import hunts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunts', '0010_hunt_liked_by_huntscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huntstep',
            name='img',
            field=models.ImageField(storage=hunts.models.get_s3_storage, upload_to='huntsteps/'),
        ),
    ]
